# Generated by Django 4.1.3 on 2022-11-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
